### ISSUE TITLE
Problem with task 1 of fashion_mnist

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#13]
For
```python
CONFIG = {'input_size':28,
          'classes':10}

def solution(input_size, classes):
    input_shape = (input_size, input_size, 1)
    images = Input(shape=input_shape)
    
    x = Conv2D(16, 3, padding='same', activation='relu')(images)
    x = Conv2D(16, 3, padding='same', activation='relu')(x)
    x = MaxPool2D()(x)
    
    x = Conv2D(16, 3, padding='same', activation='relu')(x)
    x = Conv2D(16, 3, padding='same', activation='relu')(x)
    x = MaxPool2D()(x)
    
    x = Flatten()(x)
    
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(256, activation='relu')(x)
    x = Dropout(0.5)(x)
    
    predictions = Dense(classes, activation='softmax', name='output')(x)
    
    model = Model(inputs=images, outputs=predictions)
    return model
```
I obtain
```bash
(minerva_venv) patryk@patryk-miziula:~/Documents/edukacyjne/Minerva/0401/minerva$ python run_minerva.py -- submit --problem fashion_mnist --task_nr 1 --filepath resources/fashion_mnist/problems/task1.ipynb
2018-01-11 18-34-57 minerva >>> starting experiment...
Using TensorFlow backend.
neptune: Executing in Offline Mode.
2018-01-11 18-34-58 minerva >>> Saving graph to output/path_to_your_solution/class_predictions_graph.json
[NbConvertApp] Converting notebook resources/fashion_mnist/problems/task1.ipynb to python
[NbConvertApp] Writing 2031 bytes to resources/fashion_mnist/problems/task1.py
Traceback (most recent call last):
  File "run_minerva.py", line 46, in <module>
    action()
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva_venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva_venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva_venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva_venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva_venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "run_minerva.py", line 41, in submit
    pm.submit_task(sub_problem, task_nr, filepath, dev_mode, cloud_mode)
  File "/home/patryk/Documents/edukacyjne/Minerva/0401/minerva/minerva/fashion_mnist/problem_manager.py", line 25, in submit_task
    task_handler = registered_tasks[task_nr](trainer)
KeyError: 1
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by buus2** [comment]
The same error for task 2.

**Comment by kamil-kaczmarek** [comment]
@buus2 great thanks! I will take a look.
