### ISSUE TITLE
bug in neptune send for submit mode

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#19]
After typing
```bash
neptune send run_minerva.py --environment keras-2.0-gpu-py3 --worker gcp-gpu-medium --config config.yaml -- submit --problem fashion_mnist --task_nr 2 --filepath resources/fashion_mnist/problems/task2.ipynb
```
with default `task2.ipynb` I see the following in Neptune:
```bash

18.442197 | 2018-01-17 11-30-08 minerva >>> starting experiment...
-- | --
18.801251 | Using TensorFlow backend.
34.768749 | 2018-01-17 11-30-24 minerva >>> Saving graph to /output/path_to_your_solution/class_predictions_graph.json
35.123845 | [NbConvertApp] WARNING \| pattern '/neptune/resources/fashion_mnist/problems/task2.ipynb' matched no files
35.366995 | Traceback (most recent call last):
35.367113 | File "/usr/local/lib/python3.5/dist-packages/deepsense/neptune/job_wrapper.py", line 138, in <module>
35.36723 | execute()
35.367347 | File "/usr/local/lib/python3.5/dist-packages/deepsense/neptune/job_wrapper.py", line 134, in execute
35.367463 | execfile(job_filepath, job_globals)
35.36759 | File "/usr/local/lib/python3.5/dist-packages/past/builtins/misc.py", line 82, in execfile
35.367724 | exec_(code, myglobals, mylocals)
35.367855 | File "run_minerva.py", line 46, in <module>
35.367979 | action()
35.368106 | File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
35.368223 | return self.main(*args, **kwargs)
35.368341 | File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
35.368456 | rv = self.invoke(ctx)
35.368649 | File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
35.368779 | return _process_result(sub_ctx.command.invoke(sub_ctx))
35.368922 | File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
35.369046 | return ctx.invoke(self.callback, **ctx.params)
35.369161 | File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
35.369324 | return callback(*args, **kwargs)
35.369478 | File "run_minerva.py", line 41, in submit
35.36963 | pm.submit_task(sub_problem, task_nr, filepath, dev_mode, cloud_mode)
35.369746 | File "/neptune/minerva/fashion_mnist/problem_manager.py", line 25, in submit_task
35.369861 | user_task_solution, user_config = _fetch_task_solution(filepath)
35.369984 | File "/neptune/minerva/fashion_mnist/problem_manager.py", line 33, in _fetch_task_solution
35.370102 | with TaskSolutionParser(filepath) as task_solution:
35.370218 | File "/neptune/minerva/backend/task_manager.py", line 45, in __enter__
35.370334 | if module_filename not in os.listdir(module_dir):
35.3705 | FileNotFoundError: [Errno 2] No such file or directory: '/neptune/resources/fashion_mnist/problems'
```
My `config.yaml` file is:
```bash
project-key: MIN

name: minerva

parameters:

  # Local setup
#  data_dir: path/to/your/data # for instance resources/whales/data
#  solution_dir:  output/path_to_your_solution # for instance /output/resources/whales/solution/localization

  # Cloud setup
  data_dir: /public/whales
  solution_dir: /output/path_to_your_solution

exclude:
  - resources
  - output
  - neptune.log
  - offline_job.log
  - .idea
  - .git
  - .ipynb_checkpoints

# Comment if local
pip-requirements-file: requirements.txt
```
Everything works fine for the dry run mode, i.e., for typing:
```bash
neptune send run_minerva.py \
--environment keras-2.0-gpu-py3 \
--worker gcp-gpu-medium \
--config config.yaml \
-- dry_run --problem fashion_mnist
```

**Comment by kamil-kaczmarek** [comment]
Hi @buus2,
Thanks for this. It is most likely error in Neptune cloud - I will double check the directories.

**Comment by buus2** [comment]
There are also no problems in the submit mode when you use `python run_minerva.py` or `neptune run`, so something's happening with the `--filepath` parameter.

**Comment by jakubczakon** [comment]
User solution was excluded from the files that are send to neptune. 
It can be changed in the neptune config file by changing folders that are in the `exclude: ` section.

It is fixed now and waiting for the PR to merge.

**Comment by kamil-kaczmarek** [comment]
@buus2 merged with `Bug 19`
