### ISSUE TITLE
neptune send: pip failed to install the requirements

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#46]
For
```
neptune send -- dry_eval --problem fashion_mnist
```
I obtain
```
5.019441 | [pip]    Could not find a version that satisfies the requirement  ipython==6.2.1 (from -r /tmp/tmpryjdlc (line 21)) (from versions: 0.10,  0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0,  1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0,  3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3,  4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2,  5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0,  5.4.0, 5.4.1, 5.5.0)
-- | --
5.019586 | [pip] No matching distribution found for ipython==6.2.1 (from -r /tmp/tmpryjdlc (line 21))
5.019714 | Traceback (most recent call last):
5.019839 | File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 138, in <module>
5.020117 | execute()
5.020519 | File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 119, in execute
5.020902 | install_requirements()
5.021025 | File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 51, in install_requirements
5.021172 | install_pip_requirements(os.environ['PIP_REQUIREMENTS'])
5.021552 | File "/usr/local/lib/python2.7/dist-packages/deepsense/neptune/job_wrapper.py", line 44, in _check_pip_install_result
5.021796 | raise RuntimeError('pip failed to install the requirements. '
5.024408 | RuntimeError: pip failed to install the requirements. For more details, see the stdout/stderr channels.
```

**Comment by jakubczakon** [comment]
Done, waiting for PR to merge.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @buus2 merged #49

**Comment by kamil-kaczmarek** [comment]
@buus2 Please confirm that it works fine.

**Comment by buus2** [comment]
The source of the problem is that the default Neptune worker uses Python 2. I have to specify the worker (e.g. `--worker gcp-gpu-medium`).
@kamil-kaczmarek

**Comment by kamil-kaczmarek** [comment]
@buus2 I see that worker type is included in the [User Guide](https://github.com/neptune-ml/minerva/wiki/User-Guide). Thanks, can close now.
