### ISSUE TITLE
missing package h5py

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#55]
For
```bash
neptune run -- 'dry_train --problem fashion_mnist'
```
I obtained
```bash
Traceback (most recent call last):
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 138, in <module>
    execute()
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 134, in execute
    execfile(job_filepath, job_globals)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 72, in <module>
    action()
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 20, in dry_train
    dry_run(problem, dev_mode, cloud_mode, train_mode=True)
  File "main.py", line 44, in dry_run
    pm.dry_run(sub_problem, train_mode, dev_mode, cloud_mode)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/fashion_mnist/problem_manager.py", line 22, in dry_run
    trainer.train()
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/fashion_mnist/trainer.py", line 23, in train
    'inference': False}})
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/backend/base.py", line 75, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/backend/base.py", line 81, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/backend/base.py", line 93, in _cached_fit_transform
    self.transformer.save(self.cache_filepath_step_transformer)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva/minerva/backend/models/keras/models.py", line 50, in save
    self.model.save(filepath)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/keras/engine/topology.py", line 2573, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/mnt/ml-team/homes/patryk.miziula/Minerva/minerva_venv/lib/python3.5/site-packages/keras/models.py", line 60, in save_model
    raise ImportError('`save_model` requires h5py.')
ImportError: `save_model` requires h5py.
```
Everything worked fine after `pip3 install h5py`.

Please add h5py to requirements.

**Comment by jakubczakon** [comment]
updated the requirements
